config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"
  resources :main, only: [:index, :show]

  resources :locations do
    resources :thoughts do
      resources :comments, only: [:new, :create, :destroy]
    end
  end

  resources :users
  resource  :session

  resources :locations do
    member do
      post 'add_location'
      delete 'remove_location'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :thought
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, uniqueness: :true, presence: :true
  has_many :thoughts, dependent: :destroy
  has_many :comments
  has_many :user_locations
  has_many :users, through: :user_locations
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :location
  validates :location, presence: true
  validates :title, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :thoughts
  has_many :user_locations
  has_many :locations, through: :user_locations
end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :get_current_user


def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @thought = Thought.find(params[:thought_id])
    @comment = @thought.comments.new

  end
  def create
    @location = Location.find(params[:location_id])
    @thought = Thought.find(params[:thought_id])
    @comment = @thought.comments.create!(comment_params)
    redirect_to location_path @location
  end
  def destroy
    @location = Location.find(params[:location_id])
    @thought = @location.thoughts.first
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to location_path @location
  end


  private
    def comment_params
      params.require(:comment).permit(:comment_name)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
  def new
    @location = Location.new
  end
  def create
  redirect_to root_path unless @current_user
  @location = Location.create!(location_params)
  redirect_to locations_path(@location)
end
  def show
    @location = Location.find(params[:id])
    @thought = @location.thoughts.first
    # @comment = @thought.comments.new
  end
  def edit
    redirect_to root_path unless @current_user
    @location = Location.find(params[:id])
  end
  def update
    redirect_to root_path unless @current_user
    @location = Location.find(params[:id])
    @location.update(location_params)
    redirect_to location_path(@location)
  end
  def destroy
    redirect_to root_path unless @current_user
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  def add_location
    @location = Location.find(params[:id])
    user_location = @location.user_locations.create(user: @current_user)
    redirect_to user_path(user_location.user)
  end





private
  def location_params
    params.require(:location).permit(:name, :photo_url, :has_been)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def new
    @location = Location.new
  end
  def create
  @location = Location.create!(location_params)

  redirect_to @location
end

private
  def location_params
    params.require(:location).permit(:name, :photo_url, :has_been)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @user = User.new
      @user.username = cookies[:username]
    end

    def create
      input_username = params[:user][:username]
      if User.exists?(username: input_username)
        @user = User.find_by(username: input_username)
        if @user.password === params[:user][:password]
          session[:user_id] = @user.id
          cookies[:username] = @user.username
          redirect_to root_path
        else
          flash[:alert] = "Wrong password!"
          redirect_to new_session_path
        end
      else
        flash[:alert] = "That user doesn't exist. Please sign up first below:"
        redirect_to new_user_path
      end
    end
    def destroy
      reset_session
      flash[:notice] = "You're signed out!"
      redirect_to :root
    end

end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def index
    @thoughts = Thought.all
  end
  def new
    @location = Location.find(params[:location_id])
    @thought = Thought.new
  end
  def create
    @location = Location.find(params[:location_id])
    @thought = Thought.create!(thought_params.merge(location: @location))
    redirect_to @location
  end
  def edit
    @location = Location.find(params[:location_id])
    @thought = Thought.find(params[:id])
  end
  def update
    @thought = Thought.find(params[:id])
    @thought.update(thought_params)
    redirect_to @thought.location
  end
  def destroy
    @location = Location.find(params[:location_id])
    @thought = Thought.find(params[:id])
    @thought.destroy
    redirect_to location_path(@location)
  end


private
  def thought_params
    params.require(:thought).permit(:title, :author, :body, :has_been)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

def remove_location
  @user = User.find(params[:id])
  user_location = @user.user_locations.destroy(user: @current_user)
  redirect_to user_path(user_location.user)
end



  private
  def location_params
    params.require(:location).permit(:name, :photo_url, :has_been)
  end
  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for @comment, url: location_thought_comments_path, method: :post do |f| %>

  <%= f.label :comment %>
  <%= f.text_area :comment_name %>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel Tales</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <% if @current_user %>
        <%= link_to "Welcome, #{@current_user.name}!", user_path(@current_user) %>
        <div class="out">
        <%= link_to "Sign Out", session_path, method: :delete %>
        </div>
      <% end %>
</nav>
  <% flash.each do |type, message| %>
    <p class="<%= type %>"><%= message %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for [@thought, @thought.comments.new], url: location_thought_comments_path(@location, @thought) do |f| %>

<div class="comment-box">
  <%= f.text_area :comment_name, placeholder: "Add comment...", class: "comment-placeholder" %>
</div>
<div class="submit"><%= f.submit %></div>

<% end %>

app/views/locations/edit.html.erb
<h2>Edit Location</h2>
<div class="form">
  <%= form_for @location do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>

    <%= f.submit %>
  <% end %>
</div>

app/views/locations/index.html.erb
<% if @current_user %>

<h1>Locations <%= link_to "(+)", new_location_path %></h1>

<ul>
  <% @locations.each do |location| %>
    <h3><%= link_to location.name, location %></h3>
    <div class="edit-container">
      <%= link_to "Add to profile (+)", add_location_location_path(location), method: :post %> |
      <%= link_to 'Edit', edit_location_path(location), class: "edit" %> |
      <%= link_to 'Delete', location_path(location),
      method: :delete,
      data: { confirm: 'Are you sure?' }, class: "edit" %>

    </div>
  <% end %>
</ul>

  <div class="nav">
    <h2><%= link_to "Home Page", main_index_path, class: "link" %>
  </div>

<% else %>

  <div class="nav">
    <h2><%= link_to "Please Sign In", new_session_path, class: "link" %>
  </div>

<% end %>

app/views/locations/new.html.erb
<h2>Add a location:</h2>
<div class="form">
  <%= form_for @location do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name, placeholder: "City, State"  %>

  <%= f.submit %>
  <% end %>
</div>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<div class="prompt">
  <%= link_to "Add thought", new_location_thought_path(@location), class: "add-location" %>
</div>

<ul>
  <% @location.thoughts.each do |thought| %>
  <div class="container-thought">
    <li>
      <div class="thought">
        <p>Title: <%= thought.title %> <br />
        By: <%= thought.author %></p> <br />
        <p><%= thought.body %></p>
      </div>
      <div class="edit-container">
        <%= link_to "Edit", edit_location_thought_path(@location, thought), class: "edit" %> |
        <%= link_to "Delete", location_thought_path(@location, thought), method: :delete, data: { confirm: 'Are you sure?' }, class: "edit" %>
      </div>
    </li>

    <%= render "form", :locals => {location: @location, thought: @thought} %>

    <% thought.comments.each do |c| %>
      <div class="comment-container">
        <div class="comment">
          <%= c.comment_name %>
        </div>
        <div class="delete-comment">
          <%= link_to "Delete", location_thought_comment_path(@location, @thought, c), method: :delete, data: { confirm: 'Are you sure?' }, class: "edit" %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</ul>

  <div class = "nav">
    <h2><%= link_to "Back to locations", locations_path, class: "link" %></h2>
    <h2><%= link_to "Home Page", main_index_path, class: "link" %></h2>
  </div>

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel Tales</title>
  <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

  <div class="container">

    <div class="title">
      <h1><span id="travel">Travel Tales</span><br /><span id="track">
        TRACK WHERE YOU TREK</span></h1>
    </div>

    <div class = "nav">
      <% if @current_user %>
      <h2><%= link_to "View All Locations", locations_path, class: "link" %></h2>
      <% else %>
      <h2><%= link_to "Sign Up", new_user_path, class: "link" %></h2>
      <h2><%= link_to "Sign In", new_session_path, class: "link" %></h2>
      <% end %>
    </div>

  </div>

</body>
</html>

app/views/thoughts/add_comment.html.erb
<%= form_for [@thought, @comment] do |f| %>

  <%= f.label :comment %>
  <%= f.text_area :comment %>

  <%= f.submit %>

<% end %>

app/views/thoughts/edit.html.erb
<h2>Edit Thought</h2>

<%= form_for [@location, @thought] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/thoughts/index.html.erb
<% if @current_user %>

<h1>Thoughts</h1>


<% @thoughts.each do |thought| %>
  <h2><%= thought.title %></h2>
  <p><%= thought.author %></p>
  <p><%= thought.body %></p>
  <p><%= link_to 'Edit thought', edit_location_thought_path(@location, thought) %> |
  <%= link_to 'Delete', location_thought_path(thought),
                                          method: :delete,
                                          data: { confirm: 'Are you sure?' } %></p>
<% end %>

<p><%= link_to "All thoughts", thoughts_path %></p>

<% end %>

app/views/thoughts/new.html.erb
<div class="form">
<%= form_for [@location, @thought] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body, placeholder: "Add thought..." %>

  <%= f.submit %>
<% end %>
</div>

app/views/thoughts/show.html.erb
<h2><%= @thought.title %></h2>
<h4><%= @thought.author %></h4>
<h4><%= @thought.body %></h4>

<p><%= link_to "Edit thought", edit_post_comment_path(@location, @thought) %></p>
<p><%= link_to "All thoughts", thoughts_path %></p>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<div class="form">
  <%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user %> | <%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<div class="form">
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Submit" %>
  <% end %>
</div>

<div class="nav">
  <h2><%= link_to "Home Page", main_index_path, class: "link" %></h2>
</div>

app/views/users/show.html.erb
<h2><%= @user.name %>  <%= link_to("(edit profile)", edit_user_path(@user)) if @current_user == @user %> </h2>

<span id="locations">My Locations:</span>

  <% @user.user_locations.each do |user_location| %>
    <div class="user-locations">
      <%= link_to user_location.location.name, user_location.location %>
    </div>

    <div class="edit-container">




  </div>

  <% end %>



<script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC2VjNFJ2HdQMX_dFw6XoUJFTvyjjTcU68&callback=initMap">
   </script>

   <div id="map"></div>
       <script>

         function initMap() {
           var myLatLng = {lat: -25.363, lng: 131.044};



           var locations = <%= @user.locations.map {|l| l.name}.to_json.html_safe %>
           var mapCenter, map

             locations.forEach(function(location){

               convertNameToLatLong(location, function(coords){
                 if(!mapCenter){
                   mapCenter = coords
                   map = new google.maps.Map(document.getElementById('map'), {
                     zoom: 4,
                     center: coords
                   });
                 }
                 var marker = new google.maps.Marker({
                   position: coords,
                   map: map,
                   title: 'Hello World!'
                 });
               })
             })

         }
       </script>

<script>


function convertNameToLatLong(name, callback){
  $.getJSON("https://maps.googleapis.com/maps/api/geocode/json?address=" + name, function(response){
    callback(response.results[0].geometry.location);
  })
  // callback([lat, long])
}

</script>




<div class = "nav">
  <h2><%= link_to "Back to locations", locations_path, class: "link" %></h2>
  <h2><%= link_to "Home Page", main_index_path, class: "link" %></h2>
</div>